insert into color(id,parentid,name,color) values (1,0,'Warrior','red');
insert into color(id,parentid,name,color) values (2,0,'Wizard','green');
insert into color(id,parentid,name,color) values (3,0,'Priest','white');
insert into color(id,parentid,name,color) values (4,0,'Rogue','yellow');
insert into color(id,parentid,name,color) values (5,1,'Fighter','blue');
insert into color(id,parentid,name,color) values (6,1,'Paladin','lighblue');
insert into color(id,parentid,name,color) values (7,1,'Ranger','lighgreen');
insert into color(id,parentid,name,color) values (8,2,'Mage','grey');
insert into color(id,parentid,name,color) values (9,2,'Specialist wizard','lightgrey');
insert into color(id,parentid,name,color) values (10,3,'Cleric','red');
insert into color(id,parentid,name,color) values (11,3,'Druid','green');
insert into color(id,parentid,name,color) values (12,3,'Priest of specific mythos','white');
insert into color(id,parentid,name,color) values (13,4,'Thief','yellow');
insert into color(id,parentid,name,color) values (14,4,'Bard','blue');
insert into color(id,parentid,name,color) values (15,13,'Assassin','lighblue');